package io.blue.model


object ColumnTypeNames {
  val BIGINT = "BIGINT"
  val BINARY = "BINARY"
  val BIT = "BIT"
  val CHAR = "CHAR"
  val DATETIME = "DATETIME"
  val DATE = "DATE"
  val DECIMAL = "DECIMAL"
  val FLOAT = "FLOAT"
  val IMAGE = "IMAGE"
  val INTEGER = "INTEGER"
  val INT = "INT"
  val LONG_RAW = "LONG RAW"
  val MONEY = "MONEY"
  val NCHAR = "NCHAR"
  val NTEXT = "NTEXT"
  val LONG = "LONG"
  val NVARCHAR = "NVARCHAR"
  val NUMERIC = "NUMERIC"
  val NUMBER = "NUMBER"
  val RAW = "RAW"
  val REAL = "REAL"
  val SMALL_DATETIME = "SMALLDATETIME"
  val SMALL_MONEY = "SMALL MONEY"
  val SMALLINT = "SMALLINT"
  val TEXT = "TEXT"
  val TIMESTAMP = "TIMESTAMP"
  val TINYINT = "TINYINT"
  val UNIQUEIDENTIFIER = "UNIQUEIDENTIFIER"
  val INT_IDENTITY = "INT IDENTITY"
  val BIGINT_IDENTITY = "BIGINT IDENTITY"
  val VARBINARY = "VARBINARY"
  val VARCHAR = "VARCHAR"
  val VARCHAR2 = "VARCHAR2"
  val SYSNAME = "SYSNAME"
  val XML = "XML"
  val CLOB = "CLOB"
}
